# Generated by Django 4.2.30 on 2026-05-12 04:57

import autoslug.fields
from django.db import migrations, models
import misc.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='About Us Heading')),
                ('descriptions', models.TextField(verbose_name='About Us')),
                ('image', models.FileField(default=None, max_length=200, null=True, upload_to='about_us/')),
                ('years_experiences', models.CharField(max_length=255, verbose_name='Years Experiences')),
                ('happy_visitors', models.CharField(max_length=255, verbose_name='Happy Visitors')),
                ('awards_winning', models.CharField(max_length=255, verbose_name='Awwards Winning')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Image Title')),
                ('image', models.FileField(default=None, max_length=250, null=True, upload_to='gallery_images/')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, verbose_name='Site Name')),
                ('site_keywords', models.CharField(max_length=225, verbose_name='Site Keywords')),
                ('site_email', models.EmailField(max_length=254, verbose_name='Site Email')),
                ('site_hr_email', models.EmailField(max_length=254, verbose_name='HR Email')),
                ('site_phone', models.CharField(max_length=225, verbose_name='Site Phone')),
                ('site_fax', models.CharField(max_length=20, verbose_name='Site FAX')),
                ('site_address', models.CharField(max_length=255, verbose_name='Site Address')),
                ('site_contry', models.CharField(max_length=255, verbose_name='Contry')),
                ('site_city', models.CharField(max_length=255, verbose_name='City')),
                ('site_logo', models.FileField(default=None, max_length=250, null=True, upload_to=misc.models.logo_image_upload_path)),
                ('site_description', models.TextField(verbose_name='Site Description')),
            ],
            options={
                'verbose_name': 'Web Setting',
                'verbose_name_plural': 'Website Setting',
                'ordering': ['site_name'],
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Slider Title')),
                ('sub_title', models.CharField(max_length=200, verbose_name='Slider subtitle')),
                ('description', models.TextField(verbose_name='Slider Description')),
                ('image', models.FileField(default=None, max_length=250, null=True, upload_to=misc.models.slider_image_upload_path)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True, verbose_name='Slider Slug')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_url', models.TextField(blank=True, null=True, verbose_name='Facebook URL')),
                ('x_url', models.TextField(blank=True, null=True, verbose_name='X URL')),
                ('instagram_url', models.TextField(blank=True, null=True, verbose_name='Instagram URL')),
                ('linkedIn_url', models.TextField(blank=True, null=True, verbose_name='LinkedIn URL')),
            ],
            options={
                'verbose_name': 'Social Media Link',
                'verbose_name_plural': 'Social Media Links',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Member Name')),
                ('designation', models.CharField(max_length=100, verbose_name='Member Designations')),
                ('bio', models.TextField(verbose_name='Member Bio')),
                ('image', models.FileField(default=None, max_length=250, null=True, upload_to=misc.models.team_image_upload_path)),
                ('fb_url', models.TextField(blank=True, null=True, verbose_name='Facebook URL')),
                ('twitter_url', models.TextField(blank=True, null=True, verbose_name='Twitter URL')),
                ('linkedin_url', models.TextField(blank=True, null=True, verbose_name='LinkedIn URL')),
                ('instagram_url', models.TextField(blank=True, null=True, verbose_name='Instagram URL')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Client Name')),
                ('designation', models.CharField(max_length=100, verbose_name='Client Designations')),
                ('feedback', models.TextField(verbose_name='Client Feedback')),
                ('image', models.FileField(default=None, max_length=250, null=True, upload_to=misc.models.user_image_upload_path)),
                ('rating', models.PositiveBigIntegerField(choices=[(1, '★ 1 Star'), (2, '★★ 2 Stars'), (3, '★★★ 3 Stars'), (4, '★★★★ 4 Stars'), (5, '★★★★★ 5 Stars')], verbose_name='client Ratings')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['name'],
            },
        ),
    ]
