# Generated by Django 4.2.30 on 2026-05-12 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutUse',
            new_name='AboutUs',
        ),
    ]
