# Generated by Django 4.2.30 on 2026-05-12 06:57

from django.db import migrations, models
import django.utils.timezone
import misc.models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0002_rename_aboutuse_aboutus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfo',
            name='site_contry',
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='site_country',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='awards_winning',
            field=models.CharField(max_length=255, verbose_name='Awards Won'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(default=None, max_length=200, null=True, upload_to='about_us/'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='years_experiences',
            field=models.CharField(max_length=255, verbose_name='Years of Experience'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='gallery_images/'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='site_logo',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to=misc.models.logo_image_upload_path),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to=misc.models.slider_image_upload_path),
        ),
        migrations.AlterField(
            model_name='slider',
            name='sub_title',
            field=models.CharField(max_length=200, verbose_name='Slider Subtitle'),
        ),
        migrations.AlterField(
            model_name='socialmedialinks',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook URL'),
        ),
        migrations.AlterField(
            model_name='socialmedialinks',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram URL'),
        ),
        migrations.AlterField(
            model_name='socialmedialinks',
            name='linkedIn_url',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn URL'),
        ),
        migrations.AlterField(
            model_name='socialmedialinks',
            name='x_url',
            field=models.URLField(blank=True, null=True, verbose_name='X URL'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='designation',
            field=models.CharField(max_length=100, verbose_name='Member Designation'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='fb_url',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook URL'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to=misc.models.team_image_upload_path),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram URL'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn URL'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='twitter_url',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter URL'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='designation',
            field=models.CharField(max_length=100, verbose_name='Client Designation'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to=misc.models.user_image_upload_path),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '★ 1 Star'), (2, '★★ 2 Stars'), (3, '★★★ 3 Stars'), (4, '★★★★ 4 Stars'), (5, '★★★★★ 5 Stars')], verbose_name='Client Rating'),
        ),
    ]
