FROM nginx:1.25-alpine

COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

# Create directories for static and media files
RUN mkdir -p /vol/static /vol/media \
    && chmod 755 /vol/static /vol/media
